<a href="https://colab.research.google.com/github/0279970-star/Inferential_Statistics./blob/main/Tarea_Estadistica_GitHub.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Introducción a NumPy 1

##Temas
- Conversiones de objetos enlistados a arreglos.
- Acceso a elementos de un arreglo.

In [1]:
#Tipos de objetos en Python

In [2]:
1 + 1

2

In [3]:
type(1 + 1)

int

In [4]:
1 + 1 + 0.5

2.5

In [5]:
type(1 + 1 + 0.5)

float

In [6]:
x = "Hola a todos"
x

'Hola a todos'

In [7]:
type(x)

str

##Lista de Elementos

Una lista es una enumeracion de elementos cualesquiera

In [8]:
type(1)

int

In [9]:
L1 = [1, 2, 3, 4, 5]

In [10]:
len(L1)

5

In [11]:
L2 = [6, 7, 8, 9, 10]

In [12]:
len(L1) == len(L2)

True

In [ ]:
### Operaiciones con Listas

In [13]:
L1 + L2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
### Acceso a elementos de una lista

In [14]:
L1[0]

1

In [15]:
L1[1]

2

In [16]:
L1[2]

3

In [17]:
L1[3]

4

In [18]:
L1[4]

5

## Como sumar listas elemento por elemento

In [19]:
L = [
    L1[0] + L2[0],
    L1[1] + L2[1],
    L1[2] + L2[2],
    L1[3] + L2[3],
    L1[4] + L2[4]
]
L

[7, 9, 11, 13, 15]

## Ciclo for y funcion range

In [22]:
for i in range(0, 5):
    print(i)

0
1
2
3
4


In [21]:
L = [L1[i] + L2[i] for i in range (0,5)]

## Multiplicacion de listas

In [23]:
2 * L2

[6, 7, 8, 9, 10, 6, 7, 8, 9, 10]

In [ ]:
0.5 * 12

In [26]:
M = [0.5 * L2[i] for i in range (0, 5)]

## Arreglos con Numpy

In [27]:
import numpy as np

In [28]:
L1_arreglo = np.array(L1)
L2_arreglo = np.array(L2)

L1_arreglo

array([1, 2, 3, 4, 5])

In [29]:
type(L1_arreglo)

numpy.ndarray

In [30]:
L1_arreglo + L2_arreglo

array([ 7,  9, 11, 13, 15])

In [31]:
0.5 * L2_arreglo

array([3. , 3.5, 4. , 4.5, 5. ])

##Matrices

In [32]:
lista = [i for i in range(10,30)]

In [33]:
A = np.array(lista)
A

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [34]:
matriz1 = A.reshape(4,5)
matriz1

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [35]:
matriz2 = A.reshape(10,2)
matriz2

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29]])

In [37]:
matriz3 = A.reshape(2,10)
matriz3

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [38]:
type(matriz1)

numpy.ndarray